---
- hosts: all,localhost
  gather_facts: false
  tasks:
    # Ubuntu 20.04 doesn't have python 2 pre-installed.
    # So use python3 as the interpreter.
    # Ubuntu 16.04, 18.04, and 20.04 all have it pre-installed.
    # Also, we use `sudo python3` to execute python on dev box machine.
    # It is better to align with it here to avoid `ansible-playbook` fails into another python.
    - name: set ansible_python_interpreter to python3
      set_fact:
        ansible_python_interpreter: "/usr/bin/python3"

    - name: output ansible_python_interpreter
      debug:
        var: ansible_python_interpreter

- hosts: all
  gather_facts: false
  tasks:
    - name: setup
      setup:
      delegate_to: localhost

    - name: set ansible control host IP fact
      set_fact:
        ansible_control_host_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      delegate_to: 127.0.0.1

    - name: "SSH test from dev-box to all machine of infra and worker"
      ping:


- hosts: all,localhost
  gather_facts: false
  tasks:
    - name: "set up unmet_requirements"
      set_fact:
        unmet_requirements: []

- hosts: localhost
  become: true
  become_user: root
  roles:
    - { role: requirement/devbox }
  vars:
    ansible_connection: local

- hosts: infra
  become: true
  become_user: root
  gather_facts: true
  roles:
    - { role: requirement/infra }

- hosts: worker
  become: true
  become_user: root
  gather_facts: true
  roles:
    - { role: requirement/worker }

# basic-resource role checks whether the host's basic resource meets the user input in layout.yaml
# For now, we only check CPU and memory in this role. 
- hosts: all
  become: true
  become_user: root
  gather_facts: true
  roles:
    - { role: requirement/basic-resource }

# In the following, we do different checks according to different kinds of computing device.
# To add a new kind of computing device, please add it as an ansible role in "requirement/computing-devices",
# and include the role here.
- hosts: "nvidia.com/gpu"
  become: true
  become_user: root
  gather_facts: true
  roles:
    - { role: requirement/computing-devices/nvidia.com_gpu }

- hosts: "amd.com/gpu"
  become: true
  become_user: root
  gather_facts: true
  roles:
    - { role: requirement/computing-devices/amd.com_gpu }

- hosts: "enflame.com/dtu"
  become: true
  become_user: root
  gather_facts: true
  roles:
    - { role: requirement/computing-devices/enflame.com_dtu }

- hosts: all,localhost
  tasks:
    - name: "display unmet requirements"
      fail:
        msg: "The following requirements are not met: {{ unmet_requirements | join('. ') }}"
      when: unmet_requirements|length > 0